# Generated by Django 4.1 on 2022-08-23 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portmanagementproject.base


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('original_file', models.CharField(blank=True, max_length=254)),
                ('file_name', models.CharField(blank=True, max_length=254)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_dumps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('delta_path', models.CharField(blank=True, max_length=254, null=True)),
                ('table_name', models.CharField(max_length=254)),
                ('fingerprint', models.CharField(default=portmanagementproject.base.get_fingerprint, editable=False, max_length=254, unique=True)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dump_tables', to='dashboard.dump')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=254)),
                ('field_type', models.CharField(max_length=254)),
                ('fingerprint', models.CharField(blank=True, default=portmanagementproject.base.get_fingerprint, editable=False, max_length=254, unique=True)),
                ('dump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dump_fields', to='dashboard.dump')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_fields', to='dashboard.table')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
